FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /usr/app
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
COPY . .
RUN npm install  
EXPOSE 9090
RUN chown -R node:node package.json package-lock.json src
USER node
CMD ["npm", "run", "dev"]
